name: flutter_form_helper
description: Helping you prototype and build flutter forms.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true
  
  module:
    androidX: true
    androidPackage: com.example.flutter_form_helper
    iosBundleIdentifier: com.example.flutterFormHelper
